config/routes.rb
Zhaiwuzhuitao::Application.routes.draw do

  resources :messages

  devise_for :users
  resources :blogs

  get "/pages/*id" => 'pages#show', as: :page, format: false
  root to: 'pages#show', id: 'home'

end

app/models/blog.rb
class Blog < ActiveRecord::Base
  extend FriendlyId
  friendly_id :name
  validates_presence_of :name, :content
  validates :name, uniqueness: true
end

app/models/message.rb
class Message < ActiveRecord::Base
  validates_presence_of :name, :email
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]

  # GET /blogs
  # GET /blogs.json
  def index
    @blogs = Blog.order("updated_at DESC").all
  end

  # GET /blogs/1
  # GET /blogs/1.json
  def show
  end

  # GET /blogs/new
  def new
    @blog = Blog.new
  end

  # GET /blogs/1/edit
  def edit
  end

  # POST /blogs
  # POST /blogs.json
  def create
    @blog = Blog.new(blog_params)

    respond_to do |format|
      if @blog.save
        format.html { redirect_to @blog, notice: 'Blog was successfully created.' }
        format.json { render action: 'show', status: :created, location: @blog }
      else
        format.html { render action: 'new' }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blogs/1
  # PATCH/PUT /blogs/1.json
  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to @blog, notice: 'Blog was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1
  # DELETE /blogs/1.json
  def destroy
    @blog.destroy
    respond_to do |format|
      format.html { redirect_to blogs_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = Blog.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def blog_params
      params.require(:blog).permit(:name, :summary, :keyword, :content, :weight)
    end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_message, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [ :index, :edit, :update, :destroy]

  # GET /messages
  # GET /messages.json
  def index
    @messages = Message.all
  end

  # GET /messages/1
  # GET /messages/1.json
  def show
  end

  # GET /messages/new
  def new
    @message = Message.new
  end

  # GET /messages/1/edit
  def edit
  end

  # POST /messages
  # POST /messages.json
  def create
    @message = Message.new(message_params)
    respond_to do |format|
      if @message.save
        MessageMailer.send_email(@message).deliver
        format.html { redirect_to @message, notice: 'Message was successfully created.' }
        format.json { render action: 'show', status: :created, location: @message }
      else
        format.html { render action: 'new' }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /messages/1
  # PATCH/PUT /messages/1.json
  def update
    respond_to do |format|
      if @message.update(message_params)
        format.html { redirect_to @message, notice: 'Message was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /messages/1
  # DELETE /messages/1.json
  def destroy
    @message.destroy
    respond_to do |format|
      format.html { redirect_to messages_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_message
      @message = Message.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def message_params
      params.require(:message).permit(:name, :email, :phone, :note)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  include HighVoltage::StaticPage
end

app/helpers/application_helper.rb
# -*- coding: utf-8 -*-
module ApplicationHelper
  def markdown(text)
    options = {
      hard_wrap: true,
      link_attributes: { rel: 'nofollow', target: "_blank" },
      space_after_headers: true,
      fenced_code_blocks: true
    }
    
    extensions = {
      autolink: true,
      superscript: true,
      disable_indented_code_blocks: true
    }
    
    renderer = Redcarpet::Render::HTML.new(options)
    markdown = Redcarpet::Markdown.new(renderer, extensions)
    
    markdown.render(text).html_safe
  end

  def title(title = nil)
    if title.present?
      content_for :title, title
    else
      content_for?(:title) ? content_for(:title) + ' | 在俄罗斯债务追讨' : APP_CONFIG['default_title']
    end
  end

  def meta_keywords(tags = nil)
    if tags.present?
      content_for :meta_keywords, tags
    else
      content_for?(:meta_keywords) ? content_for(:meta_keywords) : APP_CONFIG['default_keywords']
    end
  end

  def meta_description(description = nil)
    if description.present?
      content_for :meta_description, description
    else
      content_for?(:meta_description) ? content_for(:meta_description) : APP_CONFIG['default_description']
    end
  end
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/blogs/_form.html.haml
= form_for @blog do |f|
  - if @blog.errors.any?
    #error_explanation
      %h2= "#{pluralize(@blog.errors.count, "error")} prohibited this blog from being saved:"
      %ul
        - @blog.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name, {required: ''}
  .field
    = f.label :summary
    = f.text_field :summary
  .field
    = f.label :content
    = f.text_area :content, {required: ''}
  .field
    = f.label :keyword
    = f.text_field :keyword
  .field
    = f.label :weight
    = f.text_field :weight
  .actions
    = f.submit 'Save'

app/views/blogs/edit.html.haml
%h1 Editing blog

= render 'form'

= link_to 'Show', @blog
\|
= link_to 'Back', blogs_path

app/views/blogs/index.html.haml
%header
  %h1 博客列表
  %hr

- @blogs.each do |blog|
  %h3= link_to blog.name, blog_path(blog)
  %p= markdown(truncate(blog.content, length: 200))
  %p.small= blog.updated_at
  - if user_signed_in?
    .manage
      = link_to 'Show', blog, class: "button success tiny"
      = link_to 'Edit', edit_blog_path(blog), class: "button tiny" 
      = link_to 'Destroy', blog, :method => :delete, :data => { :confirm => 'Are you sure?' }, class: "button tiny alert"  


= link_to 'New Blog', new_blog_path, class: "button success" if user_signed_in?

app/views/blogs/new.html.haml
%h1 New blog

= render 'form'

= link_to 'Back', blogs_path

app/views/blogs/show.html.haml
- title @blog.name
- meta_description @blog.summary 
- meta_keywords @blog.keyword
= notice

%h1= @blog.name
= markdown(@blog.content)

= social_share_button_tag(@blog.name)

- if user_signed_in?
  = link_to 'Edit', edit_blog_path(@blog)
  \|
  = link_to 'Back', blogs_path

app/views/layouts/_analytics.html.erb
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-51128928-1', 'zhaiwu-zhuitao.com');
  ga('send', 'pageview');

</script>

app/views/layouts/_bottom.html.haml
.footer.text-center
  %p 提醒： 我们的律师公司从1994年开始在一直都从事偿还债务！！！
  = image_tag('logonew.png', height: '', width: '', class: "text-center")
  %p
    %a{href: "http://www.dolg-vozvrat.com"} 我们俄文的网站 - www.dolg-vozvrat.com

app/views/layouts/_footer.html.haml
%footer#footerpan
  .row
    .medium-12.columns.text-center
      %p 0086&nbsp;(108) 405-47-83 (汉语) 007&nbsp;(495) 514-29-37 (俄语)
      %p 地址: 俄罗斯，莫斯科，Shabolovka 街34号办公室 info@zhaiwu-zhuitao.com

app/views/layouts/_hero.html.haml
#hero.low
  .scroller

app/views/layouts/_navbar.html.haml
%section.sidenav
  %ul.side-nav
    %li= link_to_unless_current "首页", root_path
    - Blog.order("weight asc").all.each do |blog|
      %li= link_to_unless_current blog.name, blog_path(blog)

app/views/layouts/_topbar.html.haml
%header#toprow
  .row
    .small-5.medium-3.large-3.columns.logo
      = link_to image_tag('logonew.png', height: '150', width: '150'), root_path
    .small-7.medium-5.large-6.columns.slogan.text-center
      %h3 国际法律公司
      %h3 在俄罗斯讨债
      %h3 为中国企业家帮助
    .medium-4.large-3.columns.address.hide-for-small
      %p 0086&nbsp;(108) 405-47-83 (汉语)
      %p 007&nbsp;&nbsp;&nbsp;(495) 514-29-37 (俄语)
      %p info@zhaiwu-zhuitao.com
      %p 地址: 俄罗斯，莫斯科， Shabolovka 街34号办公室

app/views/layouts/analytics.html.erb
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-51128928-1', 'zhaiwu-zhuitao.com');
  ga('send', 'pageview');

</script>

app/views/layouts/application.html.haml
!!! 5
%html{lang: "en"}
  %head
    %meta{charset: "utf-8"}
    %meta{name: "viewport", content: "width=device-width, initial-scale=1.0"}
    = favicon_link_tag
    %title= title
    %meta{ name: 'keywords', content: meta_keywords } 
    %meta{ name: 'description', content: meta_description }
    = stylesheet_link_tag    "application"
    = javascript_include_tag "vendor/modernizr"
    = csrf_meta_tags
  %body
    = render "layouts/topbar"
    = content_for?(:hero) ? yield(:hero) : render("layouts/hero")
    %main{class: controller_name}
      .row 
        .small-12.medium-3.columns
          = content_for?(:navbar) ? yield(:navbar) : render("layouts/navbar")
        .small-12.medium-9.columns
          = yield
    = content_for?(:bottom) ? yield(:bottom) : render("layouts/bottom")
    = render "layouts/footer"
    = render "layouts/analytics"

    = javascript_include_tag "application", "data-turbolinks-track" => true

app/views/messages/_form.html.haml
= form_for @message do |f|
  - if @message.errors.any?
    #error_explanation
      %h2= "#{pluralize(@message.errors.count, "error")} prohibited this message from being saved:"
      %ul
        - @message.errors.full_messages.each do |msg|
          %li= msg
  .field
    = f.label :name, '姓名'
    = f.text_field :name, {required: '', placeholder: '姓名'}
  .field
    = f.label :email, '电子邮件'
    = f.text_field :email, {required: '', placeholder: "yourname@example.biz"}
  .field
    = f.label :phone, '电话'
    = f.text_field :phone, {placeholder: "18688883692"}
  .field
    = f.text_area :note, {required: '', placeholder: "你的留言"}
  .actions
    = f.submit 'Send', class: 'button success radius'

app/views/messages/edit.html.haml
%h1 Editing message

= render 'form'

= link_to 'Show', @message
\|
= link_to 'Back', messages_path

app/views/messages/index.html.haml
%h1 Listing messages

%table
  %tr
    %th Name
    %th Email
    %th Phone
    %th Note
    %th
    %th
    %th

  - @messages.each do |message|
    %tr
      %td= message.name
      %td= message.email
      %td= message.phone
      %td= message.note
      %td= link_to 'Show', message
      %td= link_to 'Edit', edit_message_path(message)
      %td= link_to 'Destroy', message, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Message', new_message_path

app/views/messages/new.html.haml
%h1 你的要求

= render 'form'

app/views/messages/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @message.name
%p
  %b Email:
  = @message.email
%p
  %b Phone:
  = @message.phone
%p
  %b Note:
  = @message.note

= link_to 'Edit', edit_message_path(@message)
\|
= link_to 'Back', messages_path

app/views/pages/_hero.html.haml
#hero.high
  .scroller
    .row
      .small-12.columns.text-center
        .alert-box{data: {alert: ""}}
          %a.close &times;
          %h1 我们尽量帮你
          = link_to '联系我们', new_message_path, class: 'button alert radius'

app/views/pages/home.html.haml
- content_for :hero do
  = render "hero"

%h1在俄罗斯讨债
%hr
%h2为中国企业家的律师
%p 如果你在俄罗斯工作时候失去了你们的钱，尽快跟我们联系。
%h3 我们会帮助你把你的钱取回来。
%p 在俄罗斯工作不容易。 在俄罗斯很多不可靠的合作伙伴。 
%p 在俄罗斯官员和警察受贿。 在俄罗斯很多中国企业家被欺骗了。
%p 在俄罗斯基本都人们不会说汉语。 没有人可以帮助中国人。 
%p 对中国企业家来说在俄罗斯做生意很难。
%h4 如果你在俄罗斯工作时候失去了你们的钱，尽快跟我们联系。
%h3 我们将尽我们所能的来帮助你。
%p 千万别忘如果你的产品和钱都有文档的话我们才可以帮你。
%h3 如果没有文件的话我们无法帮你。
%p 在俄罗斯债务追偿是艰苦的工作。这是要付钱的。
%h3 你付钱以后我们开始工作。
%p 我们熟悉您的情況之后， 我们就会告诉你有没有机会拿回来你的钱。如果没办法把你得到你的钱拿回来我们会直接告诉你的这件事。 你不要付钱！
%h3 我们不会骗你的！
%hr
%h4.red 对那些人谁欺骗了你，给他们看下面的图片。 
= image_tag('kit.jpg', height: '', width: '')
%h4.red 嘿你，俄罗斯的骗子！
%h4.red 不要欺骗中国人！ 
%h4.red 我们会一起去找你！
= social_share_button_tag("在俄罗斯讨债")